[package]
name = "oaendlig"
version = "0.1.0"
authors = ["name <e@ma.il>"]

[dependencies]
# pdcurses-sys = "0.7"
pancurses = "0.16.0"
bitflags = "1.0"
uuid = { version = "0.6", features = ["v4"] }
rand = "0.5.4"
num = "0.2.0"
